package com.arc.core.model.request.app;

import lombok.Data;

@Data
public class MusicFieldDTO {

    private String album;
    private String album_artist;
    private String album_artist_sort;
    private String album_sort;
    private String amazon_id;
    private String artist;
    private String artist_sort;
    private String barcode;
    private String bpm;
    private String catalog_no;
    private String comment;
    private String composer;
    private String composer_sort;
    private String conductor;
    private String cover_art;
    private String custom1;
    private String custom2;
    private String custom3;
    private String custom4;
    private String custom5;
    private String disc_no;
    private String disc_total;
    private String encoder;
    private String fbpm;
    private String genre;
    private String grouping;
    private String isrc;
    private String is_compilation;
    private String key;
    private String language;
    private String lyricist;
    private String lyrics;
    private String media;
    private String mood;
    private String musicbrainz_artistid;
    private String musicbrainz_disc_id;
    private String musicbrainz_releaseartistid;
    private String musicbrainz_releaseid;
    private String musicbrainz_release_country;
    private String musicbrainz_release_group_id;
    private String musicbrainz_release_status;
    private String musicbrainz_release_type;
    private String musicbrainz_track_id;
    private String musicbrainz_work_id;
    private String musicip_id;
    private String occasion;
    private String original_album;
    private String original_artist;
    private String original_lyricist;
    private String original_year;
    private String quality;
    private String rating;
    private String record_label;
    private String remixer;
    private String script;
    private String tags;
    private String tempo;
    private String title;
    private String title_sort;
    private String track;
    private String track_total;
    private String url_discogs_artist_site;
    private String url_discogs_release_site;
    private String url_lyrics_site;
    private String url_official_artist_site;
    private String url_official_release_site;
    private String url_wikipedia_artist_site;
    private String url_wikipedia_release_site;
    private String year;
    private String engineer;
    private String producer;
    private String djmixer;
    private String mixer;
    private String arranger;
}
